DB USER: postgres
PASSWORD: pgadmin

-- Database: QMDB001

-- DROP DATABASE IF EXISTS "QMDB001";

CREATE DATABASE "QMDB001"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_India.1252'
    LC_CTYPE = 'English_India.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

COMMENT ON DATABASE "QMDB001"
    IS 'Quick Medicine Database 001 ';
	

-- SCHEMA: public

-- DROP SCHEMA IF EXISTS public ;

CREATE SCHEMA IF NOT EXISTS public
    AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public
    IS 'standard public schema';

GRANT USAGE ON SCHEMA public TO PUBLIC;

GRANT ALL ON SCHEMA public TO pg_database_owner;

-- SCHEMA: QMD_PRD

-- DROP SCHEMA IF EXISTS "QMD_PRD" ;

CREATE SCHEMA IF NOT EXISTS "QMD_PRD"
    AUTHORIZATION postgres;

COMMENT ON SCHEMA "QMD_PRD"
    IS 'Quick Medicine Prod Schema';

GRANT ALL ON SCHEMA "QMD_PRD" TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "QMD_PRD"
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "QMD_PRD"
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "QMD_PRD"
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "QMD_PRD"
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;